server:
  port: 8081
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: swagger2word
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

logging:
  level:
    root: debug

# Swagger json url address
# https://petstore.swagger.io/v2/swagger.json
swagger.url: http://172.16.1.130:8209/log/v2/api-docs






